# Generated by Django 5.1.3 on 2024-11-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lunch_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lunchsession",
            options={"ordering": ["edit_time"]},
        ),
    ]
