# Generated by Django 5.1.3 on 2024-11-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lunch_sessions", "0002_alter_lunchsession_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunchsession",
            name="is_active",
        ),
    ]
