# Generated by Django 5.1.3 on 2024-11-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
